version: v2beta1
name: ext-authz-router

require:
  commands:
    - name: yq
      versionArgs: ["--version"]
      versionRegEx: "yq \\(https://github.com/mikefarah/yq/\\) version (v\\d+\\.\\d+\\.\\d+)"
      version: ">= 4"

# Variables for configuration
vars:
  DEVSPACE_USER: $(tr -d '._' <<< ${USER:-$(whoami)})
  CONTAINER_USER_HOME: /home/devuser
  REGISTRY:
    value: "ghcr.io/michaelw"
  DEV_REGISTRY:
    value: "ghcr.io/michaelw"
  IMAGE_NAME:
    value: "ext-authz-router-api"
  DEV_TAG:
    value: "dev-${DEVSPACE_USER}-${DEVSPACE_TIMESTAMP}"
  PROD_TAG:
    value: "latest" # XXX versioning scheme for production images

profiles:
  - name: with-infra
    merge:
      dependencies:
        infra:
          git: https://github.com/michaelw/devspace-starter-pack


# Images to build and push
images:
  # Development image - not pushed to production registry
  dev:
    image: ${DEV_REGISTRY}/${IMAGE_NAME}-dev
    dockerfile: ./Dockerfile
    target: dev
    buildKit: &buildKit
      {}
    tags:
      - ${DEV_TAG}
      - dev
    skipPush: true # Never push dev images to registry

  # Production image - for deployment and dependencies
  prod:
    image: ${REGISTRY}/${IMAGE_NAME}
    dockerfile: ./Dockerfile
    target: prod
    buildKit: *buildKit
    tags:
      - "${DEVSPACE_GIT_COMMIT}"
      - ${PROD_TAG}
    # This will be pushed to registry for others to use

# Deployments - Kubernetes manifests
deployments:
  ext-authz-router:
    helm:
      # https://www.devspace.sh/component-chart/docs/
      chart:
        name: ./charts/ext-authz-router

  service-red:
    namespace: service-red
    helm:
      chart:
        name: component-chart
        repo: "https://charts.devspace.sh"
      values:
        containers:
          - image: argoproj/rollouts-demo:red
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        service:
          ports:
            - name: http
              port: 80
              containerPort: http

  service-blue:
    namespace: service-blue
    helm:
      chart:
        name: component-chart
        repo: "https://charts.devspace.sh"
      values:
        containers:
          - image: argoproj/rollouts-demo:blue
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        service:
          ports:
            - name: http
              port: 80
              containerPort: http

  service-yellow:
    namespace: service-yellow
    helm:
      chart:
        name: component-chart
        repo: "https://charts.devspace.sh"
      values:
        containers:
          - image: argoproj/rollouts-demo:yellow
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        service:
          ports:
            - name: http
              port: 80
              containerPort: http

# Development configuration
dev:
  ext-authz-router:
    imageSelector: ${REGISTRY}/${IMAGE_NAME}
    devImage: ${DEV_REGISTRY}/${IMAGE_NAME}-dev

    env: []

    resources:
      requests:
        cpu: 1000m
        memory: 1024Mi

    # Patch Kubernetes resources last-mile
    patches:
      # Override security context for development
      - op: add
        path: spec.containers[*].securityContext.allowPrivilegeEscalation
        value: true

    # Sync local files to container
    sync:
      - path: ./
        startContainer: true
        excludeFile: .gitignore
      - path: "${DEVSPACE_USER_HOME}/.gitconfig:${CONTAINER_USER_HOME}/.gitconfig"
        file: true
        disableDownload: true

    # Port forwarding for development
    ports:
      - port: "3000" # API service

    persistPaths:
    - path: /go-cache
      skipPopulate: true
      # Optional path on the persistent volume to mount
      # volumePath: my-volume/app

    ssh:
      localHostname: ext-authz-router.devspace

    proxyCommands:
      - gitCredentials: true
      - command: kubectl

    workingDir: /workspaces/ext-authz-router

    terminal:
      command: bash .devcontainer/start.sh

    command: ["/entrypoint.sh"]
    args: ["air"]

    restartHelper:
      inject: true

pipelines:
  # Pipeline for development
  dev:
    flags:
    - name: logs
      short: l
    - name: vscode
    run: |-
      LOGS_ENABLED=false
      TERMINAL_ENABLED=true
      if [ $(get_flag "logs") == "true" ]; then
        LOGS_ENABLED=true
        TERMINAL_ENABLED=false
      fi

      run_dependencies --all
      ensure_pull_secrets --all
      build_images --all --except prod
      create_deployments --all
      start_dev --all --set "terminal.enabled=$TERMINAL_ENABLED" --set "logs.enabled=$LOGS_ENABLED"
      if [ $(get_flag "vscode") == "true" ]; then
        code --folder-uri vscode-remote://ssh-remote+ext-authz-router.devspace/workspaces/ext-authz-router
      fi

  # Pipeline for regular deployment
  deploy:
    run: |-
      PHASES=(
        "service-red service-blue service-yellow"
        "ext-authz-router"
      )
      run_dependencies --all
      ensure_pull_secrets --all
      build_images --all --except dev

      enabled="$(get_config_value deployments | yq 'keys | join(" ")')"
      for phase in "${PHASES[@]}"; do
        final=()
        for d in $phase; do
          if is_in "$d" "$enabled"; then
            final+=("$d")
          fi
        done
        if [ ${#final[@]} -gt 0 ]; then
          create_deployments "${final[@]}"
        fi
      done
      create_deployments --all --except ${PHASES[@]}

commands:
  # sections:
  #   build:
  #     Commands that can be executed in a dev container
  #   images:
  #     Commands related to building and pushing Docker images
  #   deploy:
  #     Commands related to deploying the service to Kubernetes
  setup:
    description: "Setup the development environment"
    section: build
    command: |
      echo "I: target=setup"
      go install github.com/go-delve/delve/cmd/dlv@v1.25.0
      go install github.com/air-verse/air@v1.62.0

  generate:
    description: "Generate required code and download dependencies"
    section: build
    command: |
      echo "I: target=generate"
      go generate -x ./...
      go mod download

  compile:
    description: "Compile the code base"
    section: build
    command: |
      echo "I: target=compile"
      devspace run generate $@
      go build -v ./cmd/...

  test:
    description: "Run all tests"
    section: build
    command: |
      echo "I: target=test"
      devspace run build $@
      go test -v ./...

  start:
    description: "Start the application"
    section: build
    command: |
      echo "I: target=start"
      if ! pgrep air >/dev/null; then
        go run ./cmd/ext-authz-router-service $@
      else
        echo "I: using air, nothing to do here"
      fi

  build-images:
    description: "Build Docker images for development and production environments"
    section: images
    command: |
      devspace build $@

  deploy:
    description: "Deploy the service to Kubernetes"
    section: deploy
    command: |
      devspace deploy $@

  dev:
    description: "Start development environment"
    section: deploy
    command: |
      devspace dev $@

  helm:
    description: "Run Helm commands"
    section: deploy
    command: |
      helm $@

  k:
    description: "Run kubectl commands"
    section: deploy
    command: |
      kubectl $@

  k9s:
    description: "Run k9s, the Kubernetes terminal UI"
    section: deploy
    command: |
      k9s $@

  logs:
    description: "View logs from the deployed service pods"
    section: deploy
    command: |
      devspace logs $@

  open-envdemo:
    description: "Open the envdemo application"
    section: ui
    command: |
      open http://envdemo.int.kube/

  open-namespaces:
    description: "Open the namespace selector"
    section: ui
    command: |
      open http://namespaces.int.kube/
