services:
  ext-authz-router:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/michaelw/ext-authz-router-api:${EXT_AUTHZ_ROUTER_IMAGE_TAG:-latest}
    image: ghcr.io/michaelw/ext-authz-router-api:${EXT_AUTHZ_ROUTER_IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - internal

networks:
  internal:
