services:
  ext-authz-router:
    entrypoint: ["/entrypoint.sh"]
    command: >
      /bin/sh -c "nohup air & sleep infinity"
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      tags: !override
        - ghcr.io/michaelw/ext-authz-router-api:dev
    image: ghcr.io/michaelw/ext-authz-router-api:dev
    volumes:
      - ./:/workspace:cached
      - go-cache:/go-cache
    ports:
      - "2345:2345"

volumes:
  go-cache:
