api-service:
  containers:
    - name: ext-authz-router-service
      image: ghcr.io/michaelw/ext-authz-router-api
      # use locally built images if available
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: "3000"
        - name: URLS_SELF_PUBLIC
          value: "http://ext-authz-router:3000"
      ports:
        - name: api
          containerPort: 3000
      readinessProbe:
        httpGet:
          path: /readyz
          port: api
        periodSeconds: 5
        failureThreshold: 3
        timeoutSeconds: 2
      livenessProbe:
        httpGet:
          path: /healthz
          port: api
        periodSeconds: 10
        failureThreshold: 3
        timeoutSeconds: 2
      startupProbe:
        httpGet:
          path: /startupz
          port: api
        periodSeconds: 5
        failureThreshold: 24
        timeoutSeconds: 2
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
      volumeMounts:
        - containerPath: /tmp
          volume:
            name: tmp-dir
            volumeMode: "01777"
  volumes:
    - name: tmp-dir
      emptyDir: {}
  service:
    ports:
      - name: http-api
        port: 3000
        containerPort: api
        appProtocol: http
