config:
  namespaces:
    awesome-penguin:
      target: red
    cool-otter:
      target: blue
    golden-retriever:
      target: yellow

api-service:
  annotations:
    eloader.stakater.com/auto: "true"
  containers:
    - name: ext-authz-router-service
      image: ghcr.io/michaelw/ext-authz-router-api
      # use locally built images if available
      imagePullPolicy: IfNotPresent
      env:
        - name: PORT
          value: "3000"
        - name: GRPC_PORT
          value: "3001"
        - name: URLS_SELF_PUBLIC
          value: "http://namespaces.int.kube/"
      ports:
        - name: api
          containerPort: 3000
        - name: grpc-authz
          containerPort: 3001
      readinessProbe:
        httpGet:
          path: /readyz
          port: api
        periodSeconds: 5
        failureThreshold: 3
        timeoutSeconds: 2
      livenessProbe:
        httpGet:
          path: /healthz
          port: api
        periodSeconds: 10
        failureThreshold: 3
        timeoutSeconds: 2
      startupProbe:
        httpGet:
          path: /startupz
          port: api
        periodSeconds: 5
        failureThreshold: 24
        timeoutSeconds: 2
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
      volumeMounts:
        - containerPath: /app/config/
          volume:
            name: config
  volumes:
    - name: tmp-dir
      emptyDir: {}
    - name: config
      configMap:
        name: ext-authz-router-config
  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "namespaces.int.kube"
    ports:
      - name: http-api
        port: 80
        containerPort: api
        appProtocol: http
      - name: grpc-api
        port: 3001
        containerPort: grpc-authz
        appProtocol: grpc
